### ISSUE TITLE
hdf5 biom vs2.0

### ISSUE THREAD

**Issue by jnpaulson** [joey711/biom#13]
Hi Joey!

Hope all is well. I was wondering if there were any plans to upgrade the biom class structure to incorporate the changes for version 2.0. I wanted to mention that I made a hacky way to read and convert a hdf5 biom vs 2.0 file into a `biom-class` object available here:
https://gist.github.com/nosson/c9cdcb8cf95e7daae468

**Comment by joey711** [comment]
done.

https://www.bioconductor.org/packages/3.3/bioc/html/biomformat.html
