### ISSUE TITLE
Biom install issue with numpy on Mac OsX 10.10.3

### ISSUE THREAD

**Issue by braukmann** [joey711/biom#16]
I recently tried installing qiime on my mac using pip.  I received the following error when trying to install qiime:

    building 'biom._filter' extension
    creating build/temp.macosx-10.10-x86_64-2.7
    creating build/temp.macosx-10.10-x86_64-2.7/biom
    clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/lib/python2.7/site-packages/numpy/core/include/numpy -I/usr/local/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c biom/_filter.c -o build/temp.macosx-10.10-x86_64-2.7/biom/_filter.o
    biom/_filter.c:258:10: fatal error: 'numpy/arrayobject.h' file not found
    #include "numpy/arrayobject.h"
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/var/folders/dd/ymw96sls33lc2pzwtyw3hcn80000gp/T/pip-build-9s6Bz1/biom-format/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/dd/ymw96sls33lc2pzwtyw3hcn80000gp/T/pip-reWvgX-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/dd/ymw96sls33lc2pzwtyw3hcn80000gp/T/pip-build-9s6Bz1/biom-format

It appears that the headers for numpy cannot be located properly and when I tried adding the using CFlags or the following command:

sudo ln -s /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy

I have also tried installing reinstalling numpy using either homebrew or pip with little luck.

Thank you,

Thomas

**Comment by nosson** [comment]
This is the R package of biom, not the python or qiime. I would recommend looking at those: https://github.com/biocore/qiime/issues

**Comment by braukmann** [comment]
Sorry about that.

Thank you.
