### ISSUE TITLE
Switch to jsonlite from RJSONIO

### ISSUE THREAD

**Issue by joey711** [joey711/biom#17]
Word on the street is that jsonlite is sometimes faster, and is actively maintained. RJSONIO seems to be in maintenance mode. 

Preliminary testing suggests that jsonlite will be easier to work with, anyway (more likely to support "round trips", etc).

**Comment by nosson** [comment]
Yeah! I think we need to make sure it treats everything the same, but take a look at the last post here:
https://github.com/joey711/biom/issues/13 where we talked about this actually and in the tests we performed `jsonlite` was faster.

**Comment by joey711** [comment]
Cool! Yeah, I remembered you had checked into it. Thanks for linking the post. For some reason I thought the difference was larger, but I'll take it. Almost-free performance gain. Why not. Moreover I think it will be more "bug-free" going forward. Prob a bigger deal for us than a few percent speed increase. I like it, though!

**Comment by joey711** [comment]
https://www.bioconductor.org/packages/3.3/bioc/html/biomformat.html

this is done...
