### ISSUE TITLE
add check that R biom package example .biom files match those in main project

### ISSUE THREAD

**Issue by jairideout** [joey711/biom#2]
Porting this issue over from the [one on the Python biom-format project](https://github.com/biom-format/biom-format/issues/134) (originally created by @joey711):

Unfortunately they have to be duplicated so that the R biom package functions as a complete standalone R package.

The location of the R-side example files within the biom-format repository is:

    biom-format/R-code/biom/inst/extdata/

**Comment by joey711** [comment]
Probably not going to do this. Either way, should be migrated to new repo:

https://github.com/joey711/biomformat
