### ISSUE TITLE
BIOM format 1.0.0 json file load_biom error

### ISSUE THREAD

**Issue by chrishah** [joey711/biom#20]
Hi,
I am looking to load a biom file that I have produced with the `biom-format` python package (version 2.1.4) into R. It's definitely in json format - it was produced using the biom-format function `Table.to_json()`.

I am using R biom package version 0.3.12. When I do:

``` R
biom.test <- read_biom('test-OTU-taxonomy.kraken.biom')
```

I get:

``` R
Error in if (!object$type %in% biomtypevals) { : 
  argument is of length zero
```

The file loads fine into [phinch](http://phinch.org/index.html). Any advice on how I could get this to work would be massively appreciated!

I attach the actual biom table (just added `.txt` so Github would accept the upload) - Thanks in advance for you help!

[test-OTU-taxonomy.kraken.biom.txt](https://github.com/joey711/biom/files/495514/test-OTU-taxonomy.kraken.biom.txt)

cheers,
Christoph

**Comment by joey711** [comment]
"biom" on CRAN should be considered deprecated and is going to disappear soon. Its improvements, including support for HDF5, are included in the [biomformat package on Bioconductor](https://www.bioconductor.org/packages/3.3/bioc/html/biomformat.html).

If you still have this problem after trying that package, re-post this issue on the biomformat repo issue tracker.

Thanks!
