### ISSUE TITLE
Install biom in R 3.4.0

### ISSUE THREAD

**Issue by tgodoy** [joey711/biom#25]
Hi, 
I'm trying to install biom package in the Last version of R (R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"), but I have some troubles.
I have the last version of bioconductor (Bioconductor 3.2 (BiocInstaller 1.20.3)). 

####
> biocLite("biomformat")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.20.3), R 3.4.0 (2017-04-21).
Installing package(s) 'biomformat'
Warning message:
package 'biomformat' is not available (for R version 3.4.0)
###

Could you help me?. Thanks a lot.

**Comment by joey711** [comment]
Looks like your version of R is updated, but you have an old version of Bioconductor. BioC versions are paired with R's minor updates (usually 6-month schedule). The current looks to be 3.5 if I'm not mistaken, whereas you have 3.2

The biomformat build report is showing everything in the clear:
http://bioconductor.org/checkResults/3.5/bioc-LATEST/biomformat/

I'll close for now. Post back again if this still fails *after* you've updated to BioC 3.5
